#!/bin/zsh

# for i in ${(o)$(ifconfig -lX "en[0-9]")};do ipconfig getsummary ${i} | awk '/ SSID/ {print $NF}';done 2> /dev/null

# for i in ${(o)$(ifconfig -lX "en[0-9]")};
# do
#     ipconfig getsummary ${i} | awk '/ SSID/ {print $NF}'
# done 2> /dev/null
networksetup -listpreferredwirelessnetworks en0 | sed -n '2 p' | tr -d '\t'
exit 0
